version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBNAME}
    volumes:
      - ../data:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080